### ISSUE TITLE
Fatal error: Uncaught Error: Class 'PDO' not found in /var/www/spotweb/lib/dbeng/dbeng_pdo_mysql.php

### ISSUE THREAD

**Issue by fryelectro** [jgeusebroek/docker-spotweb#14] opened 2019-04-09 10:39 UTC
Hi,

When creating the container, all works but after stopping and starting the docker container, I get the following error:

Fatal error: Uncaught Error: Class 'PDO' not found in /var/www/spotweb/lib/dbeng/dbeng_pdo_mysql.php:25 Stack trace: #0 /var/www/spotweb/lib/Bootstrap.php(117): dbeng_pdo_mysql->connect(‘x.x.x.x’, 'spotweb', ‘xxxxx’, 'spotweb') #1 /var/www/spotweb/lib/Bootstrap.php(34): Bootstrap->getDaoFactory() #2 /var/www/spotweb/index.php(18): Bootstrap->boot() #3 {main} thrown in /var/www/spotweb/lib/dbeng/dbeng_pdo_mysql.php on line 25

anyone knows what causes this?

**Comment by fryelectro** [comment] 2019-04-09 19:01
That is :

docker inspect --format='{{.Image}}' spotweb
sha256:64b3341137d6be2c9577566ee66b0febdef06eb8f37d71de7362c546b255e19d

**Comment by jgeusebroek** [comment] 2019-04-10 05:41
That is in fact the latest image. Are you overriding the php.ini, or any other custom settings / custom volume mounts?

**Comment by fryelectro** [comment] 2019-04-10 08:06
This is how I start the image. The only custom mount is the /var/wwww/spotweb/cache but I had the problem already before this.

docker run --restart=always -d -p 8011:80 \
    --hostname=spotweb \
    --name=spotweb \
    -v /share/Container/appdata/spotweb/config:/config:rw \
    -v /share/Container/appdata/spotweb/cache:/var/www/spotweb/cache:rw \
    -e TZ='Europe/Brussels' \
    -e SPOTWEB_DB_TYPE=pdo_mysql \
    -e SPOTWEB_DB_HOST=x.x.x.x \
    -e SPOTWEB_DB_NAME=spotweb \
    -e SPOTWEB_DB_USER=spotweb \
    -e SPOTWEB_DB_PASS=xxxxx \
    -e 'SPOTWEB_CRON_RETRIEVE=*/15 * * * *' \
    -e 'SPOTWEB_CRON_CACHE_CHECK=10 */1 * * *' \
    jgeusebroek/spotweb

**Comment by jgeusebroek** [comment] 2019-04-10 08:20
I don't think it should matter, but what docker version are you using, and what is the host operating system?

Sorry, I don't have a solution for you. I tried replicating the issue but I simply can't.

**Comment by fryelectro** [comment] 2019-04-10 19:07
HI,

I understand. Is there a way to check what this error is causing? What does it mean, not being a php/mysql specialist.

# docker version 
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   0a5102e
 Built:        Wed Nov 28 10:48:56 2018
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   0a5102e
 Built:        Wed Nov 28 10:48:56 2018
 OS/Arch:      linux/amd64
 Experimental: false

OS = Qnap firmware 4.3.6.0895 with Container station 1.9.3590

thx

**Comment by jgeusebroek** [comment] 2019-04-10 20:15
It's missing the PDO PHP extention. It is however installed in the docker image.

Try running: `docker exec -ti spotweb php -m | grep -i pdo`. It should say:

PDO
pdo_mysql
pdo_pgsql

**Comment by fryelectro** [comment] 2019-04-15 09:44
Indeed, when I run this, no pdo modules found:

[~] # docker exec -ti spotweb php -m | grep -i pdo
[~] #

Any idea how to edit the container to re-add these? Since you can’t reproduce this issue, it must has to be related to the fact I use the container on te qnap docker implementation.

However, I add the container using the following command:

docker run --restart=always -d -p 8011:80 \
    --hostname=spotweb \
    --name=spotweb \
    -v /share/Container/appdata/spotweb/config:/config:rw \
    -v /share/Container/appdata/spotweb/cache:/var/www/spotweb/cache:rw \
    -e TZ='Europe/Brussels' \
    -e SPOTWEB_DB_TYPE=pdo_mysql \
    -e SPOTWEB_DB_HOST=xxxx \
    -e SPOTWEB_DB_NAME=spotweb \
    -e SPOTWEB_DB_USER=spotweb \
    -e SPOTWEB_DB_PASS=xxx \
    -e 'SPOTWEB_CRON_RETRIEVE=*/15 * * * *' \
    -e 'SPOTWEB_CRON_CACHE_CHECK=10 */1 * * *' \
    jgeusebroek/spotweb

**Comment by jgeusebroek** [comment] 2019-08-10 15:07
Sorry, I am going to close this as it's very specific to your environment. I cannot reproduce.

**Closed by jgeusebroek** 2019-08-10 15:07 UTC
